In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b= np.array([6.5, 7.0, 8.5, 9.0])

In [5]:
a[0],b[0]

(1, 6.5)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:]

array([2, 3, 4])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[0:-2]

array([1, 2])

In [11]:
a[::2]

array([1, 3])

In [12]:
b

array([6.5, 7. , 8.5, 9. ])

In [13]:
b[0], b[-1], b[3]

(6.5, 9.0, 9.0)

In [14]:
b[[0,-2,-1]]

array([6.5, 8.5, 9. ])

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [17]:
b.ndim

1

In [18]:
A =np.array([[1, 2, 3],[4, 5, 6]])

In [19]:
A.shape

(2, 3)

In [20]:
A.size

6

In [21]:
B = np.array([
              [
                [12, 11, 10],
                [8, 9, 7]
              ],
              [
                [6, 7, 8],
                [3, 4, 5]
              ],
              [
                [6, 7, 8],
                [3, 4, 5]
              ]
            ])

In [22]:
B

array([[[12, 11, 10],
        [ 8,  9,  7]],

       [[ 6,  7,  8],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 3,  4,  5]]])

In [23]:
B.shape

(3, 2, 3)

In [24]:
B.ndim

3

# Indexing and Slicing

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [26]:
A[1][0]

4

In [27]:
A[1,0]

4

In [28]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
A[:,:1]

array([[1],
       [4],
       [7]])

In [30]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
A[:3,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
A[:2,2:]

array([[3],
       [6]])

Broadcasting and Vectorised operations

In [33]:
a= np.array([1, 2, 3, 4])

In [34]:
a+10

array([11, 12, 13, 14])

In [35]:
a

array([1, 2, 3, 4])

In [36]:
a+=100

In [37]:
a

array([101, 102, 103, 104])

In [38]:
l=[0, 1, 2, 3]

In [39]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [40]:
a= np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones([3,2],dtype = np.int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [45]:
X = np.arange(4, dtype=np.int)

In [46]:
B = np.ones_like(X)

In [47]:
B

array([1, 1, 1, 1])

In [48]:
X= np.array([[1, 2, 3],[4, 5, 6]], dtype=np.int)

In [49]:
B= np.zeros_like(X)
B

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
X = np.ones([4,4], dtype=np.int) *5

In [51]:
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [52]:
X= np.array([[1,1,1],[1,1,1]] , dtype=np.int) *5

In [53]:
X

array([[5, 5, 5],
       [5, 5, 5]])

In [54]:
X = np.zeros([3,3], dtype =np.float) +100
X

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [55]:
np.ones_like(X) * 7

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.random.randint(10,size=3)

array([6, 1, 5])

In [58]:
np.random.random((3,3,3))

array([[[0.54934989, 0.24738618, 0.00959997],
        [0.94699724, 0.66046959, 0.9517008 ],
        [0.52361085, 0.06740463, 0.94889711]],

       [[0.32123873, 0.18214332, 0.31896016],
        [0.36071468, 0.91538102, 0.54877086],
        [0.58611547, 0.77240063, 0.9882905 ]],

       [[0.99732449, 0.36339115, 0.47061866],
        [0.20929836, 0.22085451, 0.08521315],
        [0.10084108, 0.64763324, 0.41314157]]])

In [59]:
np.random.randn(3,3,3)

array([[[ 0.21581576,  0.5348614 ,  0.56413239],
        [-0.83628694, -0.10504272,  0.77975494],
        [ 0.25385776, -1.11530997,  2.13022083]],

       [[ 1.07714817,  1.58525254, -0.84211582],
        [-0.36249367, -0.2139447 , -0.70035094],
        [ 0.0497201 ,  0.74140963,  0.69361108]],

       [[-0.94767962,  0.7985121 , -1.34491728],
        [-1.37635566, -0.57668436,  1.36892378],
        [-1.44641782,  0.96478555, -1.91575635]]])

In [60]:
X =[1, 2, 3]
print(X,type(X))

Y=np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [61]:
X = np.array([5, 3, 4], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y), type(Y))

[5 3 4] 2481017394000
[5 3 4] 2481017394240 <class 'numpy.ndarray'>


In [62]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [64]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [65]:
np.arange(10, 21)[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [66]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
Z = np.zeros((10,10))
print("%d bytes" %(Z.size * Z.itemsize))

800 bytes


# Array indexation

In [68]:
X =np.array(['A', 'B', 'C', 'D', 'E', 'F'])
X[-1]


'F'

In [69]:
X[1:-1]

array(['B', 'C', 'D', 'E'], dtype='<U1')

In [70]:
X[::-1]

array(['F', 'E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [71]:
X

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1')

In [72]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0]

array([1, 2, 3, 4])

In [73]:
X[-1]

array([13, 14, 15, 16])

In [74]:
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [75]:
X[:2,:2]

array([[1, 2],
       [5, 6]])

In [76]:
X[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
rAll last elements

SyntaxError: invalid syntax (<ipython-input-77-09358e055103>, line 1)

In [ ]:
X[:,-1:]

All First elements\\ X[start of row:end of row, Start of element in the row:end of element in the row]

In [ ]:
X[:,:1]

In [ ]:
X[2:,2:]

In [ ]:
X = np.array([
    [1,   2,  3,  4, 22],
    [5,   6,  7,  8, 23],
    [9,  10, 11, 12, 24],
    [13, 14, 15, 16, 24]
])
X.max()

In [ ]:
X[-2:,-2:]

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

In [ ]:
T = X>5
T

In [ ]:
T = (X==2) | (X ==10)
X[T]

In [ ]:
X.max()

In [ ]:
a =np.arange(5)
a

In [ ]:
a+20

In [ ]:
np.dtype(int).itemsize

In [ ]:
np.dtype(float).itemsize

In [ ]:
sys.getsizeof(10**100)

In [ ]:
l = list(range(1000))

In [ ]:
%time np.sum([x**2 for x in l])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
    name='G7 Population in millions')


In [ ]:
pd.Series({
    'Canada' : 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127.061,
    'United Kingdom': 64.511,
    'United States': 318.523    
}, name = 'G7 Populaion in millions')

In [ ]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]
g7_pop

In [ ]:
pd.Series(g7_pop, index= ['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'])

In [ ]:
g7_pop.iloc[-1] = 500

In [ ]:
g7_pop.iloc[-1]